# Generated by Django 5.1.3 on 2024-12-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagories', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image_url', models.URLField(null=True)),
                ('created_at_time', models.DateTimeField(auto_now_add=True)),
                ('slugs', models.SlugField(unique=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.catagory')),
            ],
        ),
    ]
